# Generated by Django 3.2.7 on 2021-09-10 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stellar_Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('mass', models.PositiveBigIntegerField()),
                ('radius', models.BigIntegerField()),
                ('image', models.ImageField(null=True, upload_to='image')),
                ('discovered_on', models.DateField()),
                ('discovered_by', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luminosity', models.CharField(max_length=50)),
                ('star_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GalactapediaAPI.startype')),
                ('stellar_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GalactapediaAPI.stellar_object')),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravity', models.FloatField()),
                ('orbital_period', models.CharField(max_length=25)),
                ('is_dwarf', models.BooleanField(default=False)),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GalactapediaAPI.star')),
                ('stellar_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GalactapediaAPI.stellar_object')),
            ],
        ),
        migrations.CreateModel(
            name='Moon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravity', models.FloatField()),
                ('orbital_period', models.CharField(max_length=25)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GalactapediaAPI.planet')),
                ('stellar_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GalactapediaAPI.stellar_object')),
            ],
        ),
        migrations.CreateModel(
            name='Asteroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stellar_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GalactapediaAPI.stellar_object')),
            ],
        ),
    ]
